// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

export const metadata: Metadata = {
  title: "MoveID - IA que entende seu movimento",
  description: "Análise biomecânica inteligente para melhoria do movimento. Grave um vídeo e receba feedback técnico preciso com IA avançada.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body className="antialiased" style={{ fontFamily: '"Geist Sans", ui-sans-serif, system-ui, sans-serif' }}>
        {children}
      </body>
    </html>
  );
}